name: Change-version-before-release

on:
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  # but the GITHUB_REF might be not the tag but the branch then
  workflow_dispatch:

jobs:
  get-versiontag-n-update-code:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: change the version in main.py
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's|.*/v||')
          echo ${VERSION}
          sed -i 's|version=".*",|version=\"${VERSION}\",|' app/main.py
          head -n 33 app/main.py | tail -n 4

      # - name: setup git config
      #   run: |
      #     # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
      #     git config user.name "GitHub Actions Bot"
      #     git config user.email "<>"

      # - name: commit
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     # Stage the file, commit and push
      #     git add app/main.py
      #     git commit -m "Change version tag in code"
      #     git remote -v
      #     git branch -r
      #     git push origin bump-version-on-release

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: 'Bump version automatically on realease'
          add: './app/main.py'
          fetch: 'origin bump-version-on-release'
          push: 'origin bump-version-on-release' 
