name: Change-version-before-release

on:
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  # but the GITHUB_REF might be not the tag but the branch then
  workflow_dispatch:

# jobs:
#   get-versiontag-n-update-code:
#     runs-on: ubuntu-latest
#     steps:
#       # Checkout the branch
#       - name: checkout
#         uses: actions/checkout@v3

#       - name: change the version in main.py
#         run: |
#           VERSION=$(echo $GITHUB_REF | sed 's|.*/v(.*)|"\1"|')
#           echo ${VERSION}
#           sed -i 's|version=.*,|version=${VERSION},|' app/main.py
#           head -n 33 app/main.py | tail -n 4

#       - name: Commit changes
#         uses: EndBug/add-and-commit@v9
#         with:
#           default_author: github_actor
#           message: 'Bump version automatically on realease'
#           add: './app/main.py'
#           # fetch: 'origin bump-version-on-release'
#           push: 'origin HEAD:bump-version-on-release --force' 
jobs:
  upgrade-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'package.json, app.yaml'
          version-regexp: '\d+.\d+.\d+(-\w+.\d+)?'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          