name: Change-version-before-release

on:
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  # but the GITHUB_REF might be not the tag but the branch then
  workflow_dispatch:

jobs:
  pull-n-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2

      - name: change the version in main.py
        run: |
          VERSION=$(echo $GITHUB_REF | sed 's|.*/v||')
          sed -i 's|version=".*",|version="${VERSION}",|' app/main.py 

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: commit
        run: |
          # Stage the file, commit and push
          git add app/main.py
          git commit -m "Change version tag in code"
          git push origin version-2